version: '2'
services:
  measurement-service:
    container_name: measurements
    networks:
      - test_network
    expose:
      - 8080
    build: ./build/docker
    ports:
      - "8080:8082"
    environment:
      - SERVER_PORT=8082
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=measurement
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/measurement
      - SPRING_R2DBC_HOST=database
      - SPRING_R2DBC_PORT=5432
      - SPRING_R2DBC_DATABASE=measurement
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=password
    depends_on:
      - db
  db:
    image: postgres
    container_name: database
    expose:
      - 5432
    networks:
      - test_network
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=measurement
networks:
  test_network: